version: '3.8'
services:
  app:
    container_name: crypto_exchange_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/crypto_exchange
      JWT_SECRET_KEY: ratón_secreto_786
  db:
    container_name: crypto_exchange_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_exchange
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
